name: sspd_work1
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: appDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - sspd_work1:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  web_server:
    build:
      dockerfile: dockerfile
    restart: always
    ports:
      - "8000:80"

    depends_on:
      - db

volumes:
  sspd_work1:
